hugo: test
system:
  mode: development
log:
  filename: time_deposit_eod_engine.log
  maxsize: 100000000
  MaxBackups: 5
  MaxAge: 28
  Level: DEBUG
db:
  username: root
  password: nju063320
  host: 192.168.31.16
  port: 3306
  db: time_deposit_eod_engine
  maxOpenConn: 100
  maxIdleConn: 20
redis:
  addr: 192.168.31.16:6379
  password:
  poolSize: 10
  db: 0
server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
mambu:
  host: https://cbs-dev1.aladinbank.id
  apiKey: 1XXW0a679FIOoNEadSGt92ysIlr1J2hg
transactionReqMetaData:
  messageType: TRANSACTION
  externalOriTransactionID:
  externalOriTransactionDetailID:
  transactionType: 49
  terminalType: 6021
  terminalID: TDE
  terminalLocation: 1001-Head Office
  productCode: 000000
  acquirerIID: 947
  forwarderIID: 947
  issuerIID: 947
  issuerIName: Aladin
  destinationIID: 947
  currency: IDR
  tranDesc1: Opening Deposito Account
  tranDesc3: eod-engine