hugo: test
system:
  mode: development
log:
  filename: TimeDepositEODEngine.log
  maxsize: 100000000
  MaxBackups: 5
  MaxAge: 28
  Level: DEBUG
db:
  username: root
  password:
  host: localhost
  port: 3306
  db: time_deposit_eod_engine
  maxOpenConn: 100
  maxIdleConn: 20
server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60