log:
  filename: time_deposit_eod_engine.log
  maxsize: 100000000
  MaxBackups: 5
  MaxAge: 28
  Level: DEBUG
flow:
  nodeFailRetryTimes: 3
db:
  username: root
  password: nju063320
  host: 192.168.31.16
  port: 3306
  db: time_deposit_eod_engine
  maxOpenConn: 100
  maxIdleConn: 20
redis:
  addr: 192.168.31.16:6379
  password:
  poolSize: 10
  db: 0
server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
mambu:
  host: https://cbs-dev1.aladinbank.id
  apiKey: 1XXW0a679FIOoNEadSGt92ysIlr1J2hg
transactionReqMetaData:
  localHolderKey: test
  messageType: TRANSACTION
  externalOriTransactionID:
  externalOriTransactionDetailID:
  transactionType: 49
  terminalType: 6021
  terminalID: TDE
  terminalLocation: 1001-Head Office
  productCode: 000000
  acquirerIID: 947
  forwarderIID: 947
  issuerIID: 947
  issuerIName: Aladin
  destinationIID: 947
  currency: IDR
  tranDesc:
    withdrawAdditionalProfitTranDesc1: Pajak Bonus Bagi Hasil
    withdrawAdditionalProfitTranDesc3:
    withdrawBalanceTranDesc1: Deposito Disbursement
    withdrawBalanceTranDesc3:
    withdrawNetprofitTranDesc1: Bagi Hasil Deposito
    withdrawNetprofitTranDesc3:
    depositAdditionalProfitTranDesc1: Bonus Bagi Hasil Deposito
    depositAdditionalProfitTranDesc3:
    depositBalanceTranDesc1: Deposito Disbursement
    depositBalanceTranDesc3:
    depositNetprofitTranDesc1: Bagi Hasil Deposito
    depositNetprofitTranDesc3:

