log:
  filename: time_deposit_eod_engine.log
  maxsize: 100000000
  MaxBackups: 5
  MaxAge: 28
  Level: DEBUG
db:
  username: root
  password: nju063320
  host: 192.168.31.16
  port: 3306
  db: time_deposit_eod_engine
  maxOpenConn: 100
  maxIdleConn: 20
redis:
  addr: 192.168.31.16:6379
  password:
  poolSize: 10
  db: 0
server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
mambu:
  host: https://cbs-dev1.aladinbank.id
  apiKey: 1XXW0a679FIOoNEadSGt92ysIlr1J2hg
transactionReqMetaData:
  messageType: TRANSACTION
  externalOriTransactionID:
  externalOriTransactionDetailID:
  transactionType: 49
  terminalType: 6021
  terminalID: TDE
  terminalLocation: 1001-Head Office
  productCode: 000000
  acquirerIID: 947
  forwarderIID: 947
  issuerIID: 947
  issuerIName: Aladin
  destinationIID: 947
  currency: IDR
  tranDesc:
    withdrawAdditionalProfitTranDesc1: Bonus Bagi Hasil Deposito
    withdrawAdditionalProfitTranDesc3: withdraw additional profit from eod-engine
    withdrawBalanceTranDesc1: Deposito Disbursement
    withdrawBalanceTranDesc3: withdraw balance from eod-engine
    withdrawNetprofitTranDesc1: Deposito Disbursement
    withdrawNetprofitTranDesc3: withdraw netprofit from eod-engine
    depositAdditionalProfitTranDesc1: Tax Bonus Bagi Hasil Deposito
    depositAdditionalProfitTranDesc3: deposit additional profit from eod-engine
    depositBalanceTranDesc1: Deposito Disbursement
    depositBalanceTranDesc3: deposit balance from eod-engine
    depositNetprofitTranDesc1: Bagi Hasil Deposito
    depositNetprofitTranDesc3: deposit netprofit from eod-engine

